
name: Automatic Hosting to Firebase
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Inicando ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo "Copiando repo" 
        uses: actions/checkout@master
      - name: Deploy en Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}